name: Daily Sync _worker.js from zizifn/edgetunnel

on:
  schedule:
    
  workflow_dispatch:

permissions:
  contents: write  # 必须：允许推送代码

jobs:
  sync-worker:
    runs-on: ubuntu-latest

    steps:
      - name: 检出当前仓库代码（含推送权限）
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 获取上游最新 commit SHA
        id: get_sha
        run: |
          curl -s https://api.github.com/repos/zizifn/edgetunnel/commits/main \
            | grep '"sha"' | head -n 1 | cut -d '"' -f 4 > upstream_sha.txt
          echo "sha=$(cat upstream_sha.txt)" >> $GITHUB_OUTPUT

      - name: 检查是否需要更新
        id: check_update
        run: |
          if [ ! -f version.txt ]; then
            echo "首次运行，需更新"
            echo "need_update=true" >> $GITHUB_OUTPUT
          elif ! cmp -s upstream_sha.txt version.txt; then
            echo "上游有新版本，需更新"
            echo "need_update=true" >> $GITHUB_OUTPUT
          else
            echo "版本未变，无需更新"
            echo "need_update=false" >> $GITHUB_OUTPUT
          fi

      - name: 同步 _worker.js 并更新 version.txt
        if: steps.check_update.outputs.need_update == 'true'
        run: |
          curl -sL https://raw.githubusercontent.com/zizifn/edgetunnel/main/src/worker-with-socks5-experimental.js -o _worker.js
          cp upstream_sha.txt version.txt
          echo "updated=true" >> $GITHUB_ENV

      - name: 提交并推送变更（不动 README.md）
        if: env.updated == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 只添加需要的文件
          git add _2worker.js version.txt

          # 如果确实有变动则提交
          if ! git diff --cached --quiet; then
            git commit -m "自动同步 _worker.js，上游版本 $(cat version.txt)"
            git push origin HEAD
          else
            echo "无实际改动，跳过提交"
          fi
